### ISSUE TITLE
Add README with basic instructions

### ISSUE THREAD

**Issue by bencodezen** [Code-Pop/Intro-to-Vue-3#1]
Ideas of things to include:

- [ ] Prerequisites
- [ ] How to get setup
- [ ] Questions? Submit an issue

**Comment by gplanansky** [comment]
re the lesson 1 intro "If you have more experience with programming and using git, and Github, you’re going to want to head over to the course’s repo and clone the project. From there, you can switch between different branches for the starting and ending code for each lesson. For example, in the next lesson (lesson two) you can check out L2-start or L2-end for the starting and ending code, respectively."

Enlarge on that, there and in the proposed README, with an example:

git clone https://github.com/Code-Pop/Intro-to-Vue-3.git --branch L3-start --single-branch --depth 1 lesson3

Or whatever git syntax is proper.   

Consider adding, to the V M course lesson with the vscode howto material on using vscode's integrated git stuff.  Note that one of the V M course lessons has an oops moment:  "Whoa! looks like that just nuked all we've coded, but not to worry:  thank goodness for git versioning, just undo the change".   However the lesson did not speak to using the needed versioning prior.

**Comment by SummerSeaSun** [comment]
Just installed node,  vue and vue-cli switched to project directory expecting to start to code but ended like this:

```
git clone https://github.com/Code-Pop/Intro-to-Vue-3.git
cd Intro-to-Vue-3.git

~/workspace/vue3/Intro-to-Vue-3$ vue-cli-service serve
 INFO  Starting development server...
10% building 2/2 modules 0 activenode:events:353
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch '/home/tec1/workspace/vue3/Intro-to-Vue-3'
    at FSWatcher.<computed> (node:internal/fs/watchers:219:26)
    at Object.watch (node:fs:1577:34)
    at createFsWatchInstance (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqCallback.oncomplete (node:fs:200:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/tec1/.local/share/virtualenvs/vue3-9ND16rlR/lib/node_modules/@vue/cli-service/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (node:fs:200:5) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/home/tec1/workspace/vue3/Intro-to-Vue-3',
  filename: '/home/tec1/workspace/vue3/Intro-to-Vue-3'
}
 
```
npm --version 7.0.15

**Comment by digitalrep** [comment]
I would have appreciated instructions on how to build/run the app...

**Comment by waterkip** [comment]
I'm missing a package.json, so you can clone the repo and still stuck with something that doesn't work. A simple README would be welcome so we can read it, execute what is needed and be done with it and follow the course.
